### PR TITLE
Don't look for a parent if you're the parent

### PR DESCRIPTION
**Pull request by Link2Twenty**
Allow navigating to contentObjects without crash

### CODE REVIEW

**Comment by moloko** [comment]
@Link2Twenty could you check this hasn't already been resolved by #24

**Comment by Link2Twenty** [comment]
I don't think #24 fixes this, this patch allows the id to be a `contentObject` as running findAncestor("contentObjects") on a `contentObject` returns `undefined`

**Comment by moloko** [comment]
@Link2Twenty what version of the adapt framework are you using this with?

**Comment by Link2Twenty** [comment]
@moloko 4.2.0

**Comment by moloko** [comment]
it should work OK then as if `findAncestor` does return `undefined`, the check on line 99 will cause it to `return` with no further...

TBH I need to get #24 merged anyway as I know for sure it fixes #23 - and when I do that I'm afraid your PR will be out of date as it's based on code that's going to be very different after the merge. 

So it might be best if I release the new version, you test again against that and let me know if there's still a problem?

Apologies for having left that PR unmerged for so long...

**Pull request closed without merging**
